name = "download_recorder"
main = "src/worker.js"
compatibility_date = "2023-09-24"
workers_dev = true

[[routes]]
pattern = "download.thealiendoctor.com"
zone_name = "thealiendoctor.com"
custom_domain = true

[[routes]]
pattern = "stats.thealiendoctor.com"
zone_name = "thealiendoctor.com"
custom_domain = true

[placement]
mode = "smart"

[triggers]
crons = [ "0 12 * * sat" ]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "DownloadArchive"
database_id = "34a375cc-9ec7-4244-9368-b63c71fa9218"

[vars]
url = "https://discord.com/api/webhooks/1156259064595087521/fLfxylc8D6oe15-ZsnTxhpjwUkmjUIXM08ncj0GYV2pX3yykMM3hMZgbRn36qsvhd9FG"

[[kv_namespaces]]
id = "c25ceddd69d046ffb315f74ed1f3de33"
binding = "WDR"

[[kv_namespaces]]
id = "8946e1721893497689df9b9e99a5ded2"
binding = "WVR"
