name = "download_recorder"
main = "src/worker.js"
compatibility_date = "2023-09-24"

kv_namespaces = [
  { binding = "WDR", id = "c25ceddd69d046ffb315f74ed1f3de33" },
  { binding = "WVR", id = "8946e1721893497689df9b9e99a5ded2" }
]

[triggers]
crons = ["0 12 * * sat"]

[vars]
url = "https://discord.com/api/webhooks/1156259064595087521/fLfxylc8D6oe15-ZsnTxhpjwUkmjUIXM08ncj0GYV2pX3yykMM3hMZgbRn36qsvhd9FG"

[placement]
mode = "smart"